name: squarehead
version: 'git'
summary: SquareHead classic game
description: |
  SquareHead is a classic turn-based puzzle game that is played on a 32x20
  field. Cells of the field are painted in different colors. One player
  starts on one corner of the field, another on the other. In their turn,
  players "repaint" their own cell, thereby adding adjacent cells of the
  same color to it. At the end, the player with the most cells wins.

  The game has several levels of difficulty and minimalistic interface.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: data/icons/256x256/squarehead.png
base: core18

apps:
  squarehead:
    command: desktop-launch $SNAP/games/squarehead
    desktop: share/usr/applications/squarehead.desktop

parts:
  squarehead:
    source-type: git
    source: .
    plugin: cmake
    configflags:
      - -DSNAP_BUILD=YES
    after: [desktop-qt5-my]
    build-packages:
      - build-essential
      - qt5-default
      - qtbase5-dev
      - dpkg-dev
      # For Qt5LinguistTools
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - qttranslations5-l10n
      - libqt5gui5
      - libqt5widgets5
      - gnome-menus
      - mime-support
      - shared-mime-info
      - hicolor-icon-theme
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libgail-common
      - libuchardet0
      - qtwayland5
      - libqt5svg5 # for loading icon themes which are svg
      - libtiff5-dev
      - libjpeg8-dev
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs

  desktop-qt5-my:
    source: snapcraft-desktop-helpers/qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - automake
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
