name: squarehead
version: 'git'
summary: SquareHead classic game
description: |
  SquareHead is a classic turn-based puzzle game that is played on a 32x20
  field. Cells of the field are painted in different colors. One player
  starts on one corner of the field, another on the other. In their turn,
  players "repaint" their own cell, thereby adding adjacent cells of the
  same color to it. At the end, the player with the most cells wins.

  The game has several levels of difficulty and minimalistic interface.

grade: stable
confinement: strict
icon: data/icons/256x256/squarehead.png

apps:
  squarehead:
    command: desktop-launch $SNAP/games/squarehead
    desktop: usr/share/applications/squarehead.desktop
    plugs: [unity7, x11, opengl, gsettings, home, wayland, desktop, desktop-legacy]

parts:
  squarehead:
    source-type: git
    source: .
    plugin: cmake
    configflags:
      - -DSNAP_BUILD=YES
    after: [desktop-qt5]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - qttranslations5-l10n
      - libatk-adaptor
      - overlay-scrollbar-gtk2
      - libcanberra-gtk3-module
      - unity-gtk3-module

  fixicon:
    plugin: nil
    after: [squarehead]
    override-build: |
      sed -i 's|Icon=squarehead|Icon=/usr/share/icons/hicolor/256x256/apps/squarehead\.png|' $SNAPCRAFT_STAGE/usr/share/applications/squarehead.desktop
